#!/usr/bin/env python3
"""
Factorio entity sprite extractor.
Reads data-raw-dump.json (generated by: factorio.exe --dump-data)
Outputs PNG sprites to public/sprites/ for BlueprintPreview.
"""

import json
import os
import sys
from pathlib import Path
from typing import Optional

try:
    from PIL import Image
except ImportError:
    print("ERROR: pip install Pillow")
    sys.exit(1)

# ── Config ────────────────────────────────────────────────────────────────────

FACTORIO_DIR = Path(r"C:\Program Files (x86)\Steam\steamapps\common\Factorio")
DUMP_FILE    = Path(os.environ["APPDATA"]) / "Factorio" / "script-output" / "data-raw-dump.json"
OUTPUT_DIR   = Path(__file__).parent / "public" / "sprites"

MOD_PATHS: dict[str, Path] = {
    "__base__":          FACTORIO_DIR / "data" / "base",
    "__core__":          FACTORIO_DIR / "data" / "core",
    "__space-age__":     FACTORIO_DIR / "data" / "space-age",
    "__elevated-rails__":FACTORIO_DIR / "data" / "elevated-rails",
    "__quality__":       FACTORIO_DIR / "data" / "quality",
}

# All entity types that appear in blueprints
BUILDABLE_TYPES = {
    "transport-belt", "underground-belt", "splitter", "linked-belt",
    "inserter",
    "container", "logistic-container", "linked-container",
    "pipe", "pipe-to-ground", "pump", "offshore-pump", "storage-tank",
    "assembling-machine", "furnace", "mining-drill",
    "electric-pole",
    "wall", "gate",
    "ammo-turret", "electric-turret", "fluid-turret", "artillery-turret",
    "roboport", "logistic-robot", "construction-robot",
    "lamp",
    "solar-panel", "accumulator",
    "nuclear-reactor", "heat-exchanger", "heat-pipe",
    "steam-turbine", "generator", "boiler",
    "chemical-plant", "oil-refinery", "pumpjack",
    "beacon",
    "lab",
    "centrifuge",
    "radar",
    "rocket-silo",
    "straight-rail", "curved-rail", "half-diagonal-rail",
    "train-stop",
    "rail-signal", "rail-chain-signal",
    "land-mine",
    "power-switch",
    "programmable-speaker",
    "arithmetic-combinator", "decider-combinator", "constant-combinator",
    "selector-combinator",
    # Space Age
    "space-platform-hub", "agricultural-tower",
    "fusion-reactor", "fusion-generator",
    "lightning-attractor", "lightning-collector",
    "biolab", "electromagnetic-plant", "recycler",
    "cryogenic-plant", "heating-tower",
    "thruster", "asteroid-collector",
    "captive-biter-spawner",
}

# ── Helpers ───────────────────────────────────────────────────────────────────

def resolve(path_str: str) -> Optional[Path]:
    for prefix, real in MOD_PATHS.items():
        if path_str.startswith(prefix):
            rel = path_str[len(prefix):].lstrip("/\\")
            p = real / rel
            return p if p.exists() else None
    p = Path(path_str)
    return p if p.exists() else None


def use_hr(s: dict) -> dict:
    hr = s.get("hr_version")
    return hr if isinstance(hr, dict) and hr.get("filename") else s


def is_shadow(layer: dict) -> bool:
    return bool(layer.get("draw_as_shadow") or layer.get("draw_as_light") or layer.get("draw_as_glow"))


def autocrop(img: Image.Image) -> Image.Image:
    """Remove transparent padding around the image content."""
    bbox = img.getbbox()
    if bbox and bbox != (0, 0, img.width, img.height):
        return img.crop(bbox)
    return img


def crop_frame(s: dict, frame: int = 0) -> Optional[Image.Image]:
    """Crop frame N from a sprite-sheet dict."""
    s = use_hr(s)
    fn = s.get("filename")
    if not fn:
        return None
    path = resolve(fn)
    if not path:
        return None
    try:
        img = Image.open(path).convert("RGBA")
    except Exception:
        return None

    # Frame size
    w = s.get("width") or s.get("size") or 0
    h = s.get("height") or s.get("size") or 0
    if not w or not h:
        return img  # whole image

    # Frame grid position
    bx = s.get("x", 0)
    by = s.get("y", 0)
    ll = s.get("line_length") or max(1, s.get("frame_count", 1))
    col = frame % ll
    row = frame // ll
    x = bx + col * w
    y = by + row * h

    # Clamp to image
    if x + w > img.width or y + h > img.height:
        x, y = bx, by
    if x + w > img.width or y + h > img.height:
        return None

    crop = img.crop((x, y, x + w, y + h))
    scale = s.get("scale", 1.0)
    if scale and scale != 1.0:
        nw = max(1, round(w * scale))
        nh = max(1, round(h * scale))
        crop = crop.resize((nw, nh), Image.LANCZOS)
    return crop


def extract(s: dict, frame: int = 0, do_autocrop: bool = True) -> Optional[Image.Image]:
    """Extract image from sprite def (handles layers). Autocrop transparent edges."""
    if not isinstance(s, dict):
        return None
    if "layers" in s:
        layers = [l for l in s["layers"] if isinstance(l, dict) and not is_shadow(l)]
        if not layers:
            layers = [l for l in s["layers"] if isinstance(l, dict)]
        result: Optional[Image.Image] = None
        for layer in layers[:4]:
            img = crop_frame(layer, frame)
            if img is None:
                continue
            if result is None:
                result = img.copy()
            elif img.size == result.size:
                result.paste(img, (0, 0), img)
        if result and do_autocrop:
            return autocrop(result)
        return result
    img = crop_frame(s, frame)
    if img and do_autocrop:
        return autocrop(img)
    return img


def directional(s: dict) -> dict[str, Optional[Image.Image]]:
    """
    Return {'N':img, 'E':img, 'S':img, 'W':img} for directional sprites
    or {'N':img} / {'':img} for non-directional.
    """
    if not isinstance(s, dict):
        return {}
    DIR_MAP = {"north":"N","east":"E","south":"S","west":"W",
               "up":"N","right":"E","down":"S","left":"W"}
    if any(k in s for k in DIR_MAP):
        out: dict[str, Optional[Image.Image]] = {}
        for src, dst in DIR_MAP.items():
            sub = s.get(src)
            if isinstance(sub, dict):
                img = extract(sub)
                if img:
                    out[dst] = img
        return out
    # Single sprite
    img = extract(s)
    return {"N": img} if img else {}


def icon_fallback(entity: dict) -> Optional[Image.Image]:
    """Load entity icon as last resort."""
    icons = entity.get("icons")
    if isinstance(icons, list) and icons:
        path_str = icons[0].get("icon") or ""
    else:
        path_str = entity.get("icon") or ""
    if not path_str:
        return None
    path = resolve(path_str)
    if not path:
        return None
    try:
        return Image.open(path).convert("RGBA")
    except Exception:
        return None


# ── Per-entity-type sprite finders ────────────────────────────────────────────

def find_sprites(entity: dict, etype: str) -> dict[str, Image.Image]:
    """Return direction-keyed sprite dict for one entity."""

    # 1. graphics_set.animation  (assembling machines, furnaces, mining drills, …)
    gs = entity.get("graphics_set")
    if isinstance(gs, dict):
        anim = gs.get("animation")
        if isinstance(anim, dict):
            result = directional(anim)
            if result:
                return {k: v for k, v in result.items() if v}

    # 2. Direct picture / base_picture / sprite  (chests, pumpjack base, …)
    for field in ("picture", "base_picture", "sprite"):
        v = entity.get(field)
        if isinstance(v, dict):
            result = directional(v)
            if result:
                return {k: v2 for k, v2 in result.items() if v2}

    # 3. structure with directional sub-keys  (splitter, underground-belt body, …)
    struct = entity.get("structure")
    if isinstance(struct, dict):
        if any(k in struct for k in ("north","east","south","west")):
            result = directional(struct)
            if result:
                return {k: v for k, v in result.items() if v}
        # direction_in / direction_out (underground-belt input mouth)
        di = struct.get("direction_in")
        if isinstance(di, dict):
            sheet = di.get("sheet") or di
            img = extract(sheet)
            if img:
                return {"N": img}

    # 4. pictures — electric poles, pipe, …
    pics = entity.get("pictures")
    if isinstance(pics, dict):
        if any(k in pics for k in ("north","east","south","west")):
            result = directional(pics)
            if result:
                return {k: v for k, v in result.items() if v}
        # layers at top level  (electric poles)
        img = extract(pics)
        if img:
            return {"N": img}

    # 5. belt_animation_set — extract 4 cardinal directions
    # Default BeltAnimationSetAssets indices (1-based in Factorio API):
    #   east_index=1 → row 0, west_index=2 → row 1,
    #   north_index=3 → row 2, south_index=4 → row 3
    bas = entity.get("belt_animation_set")
    if isinstance(bas, dict):
        anim_set = bas.get("animation_set")
        if isinstance(anim_set, dict):
            fc = anim_set.get("frame_count", 1)
            ll = anim_set.get("line_length") or fc
            # Row index for each direction (0-indexed = Factorio 1-indexed - 1)
            dir_rows = {
                "E": bas.get("east_index",  1) - 1,
                "W": bas.get("west_index",  2) - 1,
                "N": bas.get("north_index", 3) - 1,
                "S": bas.get("south_index", 4) - 1,
            }
            result: dict[str, Optional[Image.Image]] = {}
            for dir_name, row in dir_rows.items():
                # frame 0 of this direction = absolute frame index row * fc
                abs_frame = row * fc
                img = extract(anim_set, abs_frame)
                if img:
                    result[dir_name] = img
            if result:
                return result

    # 6. platform_picture  (inserter base plate)
    plat = entity.get("platform_picture")
    if isinstance(plat, dict):
        sheet = plat.get("sheet") or plat
        img = extract(sheet)
        if img:
            return {"N": img}

    # 7. Various animation field names
    for field in ("animation","animations","base","base_animation",
                  "vertical_animation","idle_animation","on_animation",
                  "working_animation","rotor","rotor_animation"):
        v = entity.get(field)
        if isinstance(v, dict):
            result = directional(v)
            if result:
                return {k: v2 for k, v2 in result.items() if v2}

    # 8. Icon fallback
    img = icon_fallback(entity)
    if img:
        return {"": img}

    return {}


# ── Main ──────────────────────────────────────────────────────────────────────

def main() -> None:
    print(f"Dump : {DUMP_FILE}")
    if not DUMP_FILE.exists():
        print("Run factorio.exe --dump-data first")
        sys.exit(1)

    print("Loading JSON …")
    with open(DUMP_FILE, encoding="utf-8") as f:
        data_raw = json.load(f)

    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    print(f"Output: {OUTPUT_DIR}\n")

    total = ok = 0
    failed: list[str] = []

    for etype in sorted(BUILDABLE_TYPES):
        type_data = data_raw.get(etype)
        if not type_data:
            continue

        for ename, entity in type_data.items():
            flags = entity.get("flags") or []
            if "hidden" in flags or entity.get("hidden"):
                continue

            total += 1
            sprites = find_sprites(entity, etype)

            if not sprites:
                print(f"  FAIL  {ename}")
                failed.append(ename)
                continue

            dirs = [d for d in sprites if sprites[d]]
            if dirs == ["N"] or dirs == [""]:
                # Non-directional — save without suffix
                img = sprites[dirs[0]]
                img.save(OUTPUT_DIR / f"{ename}.png", "PNG")
                print(f"  OK    {ename}  {img.size}")
            else:
                # Directional — save with direction suffix
                for d, img in sprites.items():
                    if img:
                        img.save(OUTPUT_DIR / f"{ename}-{d}.png", "PNG")
                print(f"  OK    {ename}  ({', '.join(d for d in dirs)})")
            ok += 1

    print(f"\n{'-'*50}")
    print(f"Done: {ok}/{total} extracted  |  {len(failed)} failed")
    if failed:
        print("Failed:")
        for n in failed:
            print(f"  • {n}")


if __name__ == "__main__":
    main()
